### ISSUE TITLE
dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.

### ISSUE THREAD

**Issue by Rahulsunny11** [Chris3691/Dash-Flask-Users#3]
Hi, I tried running your project by editing config.txt file and i got the following error please help me with this 
thank you 

`127.0.0.1 - - [30/Jul/2020 12:06:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2020-07-30 12:06:00,461] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files (x86)\python38-32\lib\site-packages\flask\app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "c:\program files (x86)\python38-32\lib\site-packages\flask\app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\dash\dash.py", line 1502, in _setup_server
    self._validate_layout()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\dash\dash.py", line 1466, in _validate_layout
    raise exceptions.NoLayoutException(
dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.
127.0.0.1 - - [30/Jul/2020 12:06:00] "[35m[1mGET / HTTP/1.1[0m" 500 -`

**Comment by yts61** [comment]
what did you edit? you only have to edit the sql path with your sql account username, password, and database name.
the square bracket above you don't have to change it.


> Hi, I tried running your project by editing config.txt file and i got the following error please help me with this
> thank you
> 
> `127.0.0.1 - - [30/Jul/2020 12:06:00] "�[35m�[1mGET / HTTP/1.1�[0m" 500 - [2020-07-30 12:06:00,461] ERROR in app: Exception on / [GET] Traceback (most recent call last): File "c:\program files (x86)\python38-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "c:\program files (x86)\python38-32\lib\site-packages\flask\app.py", line 1808, in full_dispatch_request self.try_trigger_before_first_request_functions() File "c:\program files (x86)\python38-32\lib\site-packages\flask\app.py", line 1855, in try_trigger_before_first_request_functions func() File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\dash\dash.py", line 1502, in _setup_server self._validate_layout() File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\dash\dash.py", line 1466, in _validate_layout raise exceptions.NoLayoutException( dash.exceptions.NoLayoutException: The layout was `None`at the time that`run_server`was called. Make sure to set the`layout` attribute of your application before running the server. 127.0.0.1 - - [30/Jul/2020 12:06:00] "�[35m�[1mGET / HTTP/1.1�[0m" 500 -`

**Comment by Rahulsunny11** [comment]
hi @yts61 

> [database]
con = mysql+postgres://claudopxagsyst:89a584f83000f029f06fa7dc269995715dd3521dc087069eff093e66da7f3062@ec2-54-197-254-117.compute-1.amazonaws.com:5432/d1p8n22i2njobp

this is the change I made .

**Comment by Rahulsunny11** [comment]
I am using heroku's postgressql database here

**Comment by DanielHHowell** [comment]
Also running into this same issue when attempting to use sqlite `con = sqlite:///$PWD/app.db`.
`
@Rahulsunny11 Where you able to resolve this at all?

**Comment by RomanIssabayev** [comment]
@DanielHHowell @Rahulsunny11 did you guys managed to resolve this? Also got stacked with connecting it to sqlite.
UPD.
SOLVED

**Comment by wakadinali** [comment]
I'm running the app locally and the database on mysql but the user table won't update unless I refresh the flask server and I also cannot login. What could be the problem?
Also no error is being displayed.

**Comment by biomchen** [comment]
> I'm running the app locally and the database on mysql but the user table won't update unless I refresh the flask server and I also cannot login. What could be the problem?
> Also no error is being displayed.

same issue. check the local mysql db connection, no problems at all. wonder somewhere has broken pipe. let me know if you have figured it out already. thank you.

**Comment by biomchen** [comment]
> I'm running the app locally and the database on mysql but the user table won't update unless I refresh the flask server and I also cannot login. What could be the problem?
> Also no error is being displayed.

figure out the solution to the problem:

```python
 from werkzeug.security import generate_password_hash
```

 and added a line of codes in all three callbacks in login.py:

```python
        if user:
            pwhash = generate_password_hash(user.password)
            if check_password_hash(pwhash, password):
```
then you should be able to login and to edit the pages.

**Comment by xanatower** [comment]
> > I'm running the app locally and the database on mysql but the user table won't update unless I refresh the flask server and I also cannot login. What could be the problem?
> > Also no error is being displayed.
> 
> figure out the solution to the problem:
> 
> ```python
>  from werkzeug.security import generate_password_hash
> ```
> 
> and added a line of codes in all three callbacks in login.py:
> 
> ```python
>         if user:
>             pwhash = generate_password_hash(user.password)
>             if check_password_hash(pwhash, password):
> ```
> 
> then you should be able to login and to edit the pages.

Thank you so much. I was stuck here for a while until i saw your comment!
